#!/bin/bash

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULES_DIR="$BASE_DIR/modules"
VENV_DIR="$MODULES_DIR/venv"

# Create python virtual env if it doesn't exist
if [ ! -d "$VENV_DIR" ]; then
    echo "[*] Creating Python virtual environment..."
    # Gopherus uses Python 3
    python3 -m venv "$VENV_DIR"
    if [ $? -ne 0 ]; then
        echo "[!] Failed to create virtual environment. Ensure Python 3 'venv' module is installed."
        exit 1
    fi
    echo "[*] Installing dependencies..."
    "$VENV_DIR/bin/pip" install argparse requests
fi

# Check if the tool is installed
if [ ! -f "/usr/local/bin/gopherus" ] && [ ! -L "/usr/local/bin/gopherus" ]; then
    echo "[!] Tool is not installed. installing.."
    sudo "$MODULES_DIR/install.sh"
    if [ $? -ne 0 ]; then
        echo "[!] Installation failed."
        exit 1
    fi
    echo "[*] Installation successful."
fi

# Execute command as args
cd "$MODULES_DIR" && "$VENV_DIR/bin/python" gopherus.py "$@"
